[package]
name = "grit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.28"
is_executable = "1.0.1"
sha1_smol = { version = "1.0.0", features = ["std"] }
walkdir = "2.5.0"
